### ISSUE TITLE
Add WP filter for transforming field values

### ISSUE THREAD

**Issue by doup** [htmlburger/carbon-fields#107]
It would be nice to have a filter (e.g: `carbon_field_value`) that allows to massage the values for some kind of fields. In my use case, I would use it to convert the "image" type fields into `TimberImage` objects. This also could be used for wrapping `complex` or `map` fields into PHP objects which would augment and ease the use of these.

``` php
// Timber integration
add_filter('carbon_field_value', function($value, $type) {
    if ($type == 'image') {
        return new TimberImage($value);
    } else {
        return $value;
    }
});
```

**Comment by magadanskiuchen** [comment]
Are there any particular issues you're experiencing with the `get_post_metadata` filter?

https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/meta.php#L486 -- this gets called on `get_post_meta`, which is used by the Carbon fields.

Furthermore there are similar functions for other metadata DB entries.

I am concerned about the idea to hook to such filter and return an object, rather than scalar value. In most cases a scalar will be expected (the exceptions would be `map` and `complex` fields, but the output varies based on additional argument passed to the function).

Wouldn't it make sense to create a wrapper function to use instead, which will instantiate the object you need based on the value returned by `carbon_get_post_meta()`?

**Comment by doup** [comment]
Thanks for the ideas, I think that maybe for the time being is better to use a wrapper as it'll be more transparent to the theme developer that there is some kind of value massaging behind the scenes.

On the `get_post_meta` suggestion, unless I miss something, that's not useful since I can't know what type of field I'm processing and can't cast to the desired object.

**Comment by doup** [comment]
I've created a data transformer which casts the container values. So `checkbox` becomes of type `bool` or `image` of type `TimberImage` (user configurable, of course):
https://gist.github.com/doup/a5cb00062e5190a24c028dc9963318f9

**Do you think it's worth having this as part of the plugin?**

Close this if you think it doesn't belong here. At least I wanted to put it here so it can be useful to someone.

**Comment by atanas-angelov-dev** [comment]
@doup ,

Thank you for the contribution, however, this will not be needed for 2.0 since type transformations are already built-in (each field transforms it's own values, including in complex groups).  
For example, the checkbox field now returns real boolean by default without having to specify a type.

**Comment by doup** [comment]
OK! Thanks for the great work!
