### ISSUE TITLE
Is Carbon Fields Dead?

### ISSUE THREAD

**Issue by greabs** [htmlburger/carbon-fields#1076]
It has been asked before , but since there has been very little activity , the question is still relevant; is the Carbon Fields project dead? 
I love the library and have yet to find a suitable alternative, but it looks like not much is happeing anymore and there are a bunch of tickets that really need solving. I can't speak for other, but we would have no issue with even paying a bit for using this library as long as it is (continuously) supported! 

Thanks

**Comment by ChipRyan** [comment]
+1 for eventual donations too if we could only get a link or something. I've been using the library for the past couple of years on all my projects and would contribute to see it further updated.

**Comment by emohamed** [comment]
Carbon Fields is not dead, we still maintain it because it's backing thousands of projects developed by our company.

However, there are a few trends that are making it harder for us(htmlBurger) to allocate resources to further developments on the project:

 1. All people that initially developed the library(and have solid understanding of it) moved on to work in other companies, or switched projects internally. Involving new people in a project with the size and complexity of Carbon Fields is a costly undertaking - 3 months for a seasoned developer
 2. The direction of WordPress to Gutenberg and full-site-editing will make Carbon Fields less relevant. It doesn't make too much sense to invest in a product that is not aligned with the core product it's built for
 3. The community around Carbon Fields doesn't have the critical mass for us to make business around it. I appreciate all the people that are using and contributing, and I really hope that we make developers' lives easier with Carbon Fields. However, the 99% of WordPress developers would pick ACF instead of Carbon Fields

With all that being said, we do not intend to stop supporting Carbon Fields - we will make sure that current features continue to work on new WordPress core versions. However, it's not likely that we'll release new major version or ship major new features.
