### ISSUE TITLE
User meta are visible for admin but not for users

### ISSUE THREAD

**Issue by danielezerosi** [htmlburger/carbon-fields#1151]
## Version

  - Carbon Fields: 3.5.1
  - WordPress: 6.1.1
  - PHP: 8.0

## Expected Behavior
User should see custom user meta but he does not

## Actual Behavior
Same issu as https://github.com/htmlburger/carbon-fields/issues/21. Only admin see user meta

## Container definition
```php
Container::make('user_meta', 'Address')
    ->add_fields(array(
        Field::make('text', 'crb_city_and_post', 'City and post code'),
        Field::make('text', 'crb_street', 'Street Name'),
    ));

## Steps to Reproduce the Problem
add container as example and login in backend as user and not as admin. go to profile

## Comments

**Comment by HTMLBurger-NG** [comment]
Hi @danielezerosi ,

By default, only users with the `manage_options` capability have access to this container. In order to override this behavior, please take a look at the `carbon_fields_user_meta_container_admin_only_access` filter.

The hook allows you to override the default requirement for the manage_options capability in order to interact with this container.

Add the following to your functions.php to disable this filter entirely:

`add_filter( 'carbon_fields_user_meta_container_admin_only_access', '__return_false' );`
