### ISSUE TITLE
Show on post type page compatibility

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#168]
@m1r0 Why not leave show_on_template default to use the post type 'page' unless otherwise defined in the show_on_post_type, purely for backwards compatibility reasons?

Reference #160

**Comment by m1r0** [comment]
Good point, I totally agree. Thanks for the suggestion!

**Comment by atanas-angelov-dev** [comment]
`show_on_template()` will now force the 'page' post type requirement for WP versions < 4.7 (https://github.com/htmlburger/carbon-fields/commit/7a4f07d6b87f9d21da441b932b4964d27e039b90)

**Comment by Santana1053** [comment]
This works, but not quite what I had in mind. What I meant was that if show_on_post_type() is not set along with show_on_template(), then it will infer the 'page' post type

**Comment by atanas-angelov-dev** [comment]
The default post_type for post_meta containers has always been 'post' (and it makes sense since 'post' is the core post type) and having secret functionality like `show_on_template()` changing the default value is something we want to avoid (in addition this breaks Single Responsibility Principle). With this change it is always clear what post type a certain container is assigned to - either 'post' by default or whatever is passed to `show_on_post_type()` (ignoring pre-WP4.7 which behaves differently for backwards compatibility).

Having to write `->show_on_post_type( 'page' )` whenever you want to add a container to a template on pages is a minuscule cost to avoid code smells.

**Comment by Santana1053** [comment]
Yes the default post type for post_meta containers has been 'post'. But posts don't have page templates. So using `show_on_template()` always defaulted to the `page` post type. So in all of my previous projects, all I have specified is `show_on_template()` and I never had to add `show_on_post_type('page')`. However upgrading to CB1.5 now will cause my page templates to not show metadata unless I go through each project and update the code and add `show_on_post_type('page')` as well. If this plugin was just a simple library that was versioned that wouldn't be a problem, but since this plugin is available as a plugin from the wordpress repository, I don't have any control over whether or not the plugin gets updated to this version.
