### ISSUE TITLE
Multiple image upload to complex field

### ISSUE THREAD

**Issue by eenagy** [htmlburger/carbon-fields#169]
When uploading multiple images on complex fields, new complex fields are created.
Excepted behaviour would be to populate the already existing ones with the image url/id.
Or would be really nice if there would be an option to choose from...

**Comment by atanas-angelov-dev** [comment]
Hi @eenagy,

Thanks for the feedback!

What behavior is expected really depends on the use case.
For example, if you have added 10 photos and you wish to add 10 more you will have to add them 1 by 1 or multiple select will overwrite your first 10. We believe it's much easier to remove excess photos rather than add more 1 by 1.
