### ISSUE TITLE
Conditional logic removes metadata

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#176]
One of the biggest issues I have with Carbon Fields is when using conditional logic. I love the ability to show or hide certain fields depending on another field. However, when a field is hidden and the post is updated, the metadata for that field is removed.

What I am proposing is an option for the conditional logic function that instead of removing or showing a field, would just disable or enable the field (make non-editable). This would preserve the metadata when updating the post.

Alternatively adding an option to the conditional logic function that will write all the fields to the database regardless of if they are shown or not.

**Comment by atanas-angelov-dev** [comment]
Hi @Santana1053,

set_conditional_logic() was designed with performance considerations in mind (e.g. avoid database bloating with unused data thus reducing query times etc.) rather than being a simple cosmetic hide/show.

This feature is currently not on our roadmap, however, if data persistence for disabled fields is an important aspect of your use-case, feel free to submit a PR for this feature.
