### ISSUE TITLE
It's better to disable fields rather then hide when Conditional Logic is applied

### ISSUE THREAD

**Issue by stsdc** [htmlburger/carbon-fields#22]
Hi there, 
I have a proposition to change behaviour of Fields when Conditional Logic is applied. I think, it's better to just disable fields.
e.g. :

```
Field::make('select', 'crb_show_socials', 'Show Socials')
    ->add_options(array(
        'yes' => 'Yes',
        'no' => 'No',
)),
Field::make('text', 'crb_facebook', 'Facebook URL')
    ->set_conditional_logic(array(
        'relation' => 'AND', 
        array(
           'field' => 'crb_show_socials',
           'value' => 'yes', 
           'compare' => '=', 
       )
)),
```

![disabled field](https://cloud.githubusercontent.com/assets/6031763/14652419/83ce870a-0674-11e6-8cae-88ec60be54f9.png)

I'm not an expert in UX, but when you have a few more things in a Field and they just disappear changing height of page and position of other fields, It may be disrupting. Especially, when on place of field that disappeared, jumps field with a similar name.

**Comment by tyxla** [comment]
Hey @stsdc,

Although this might make sense in some cases, I'm more inclined to disagree with you. If your conditional logic enables/disables one field only, it may make sense to just disable it instead of hiding. But if you have an interface with a lot of conditional fields (say 5 groups with different logic, with 3 fields each), the lot of disabled fields will confuse the users more than if we're just hiding them.

An optional feature here is to allow fields to be disabled when using conditional logic. This could be done through an additional parameter of the `set_conditional_logic()` method.

Some more opinions here would be useful.

**Comment by m1r0** [comment]
Hiding the fields when the conditional logic kicks in is a standard approach, most users expect just that.

I like the idea that @tyxla suggested - adding an optional feature so you can set the conditional logic behavior.

**Comment by m1r0** [comment]
We decided that the conditional logic behavior will remain the same. Consider creating a new ticket for the above-mentioned feature.

Closing this issue.
