### ISSUE TITLE
Association field UI for hierarchical Post Types and Taxonomies

### ISSUE THREAD

**Issue by pkostadinov-2create** [htmlburger/carbon-fields#227]
It would be a cool view, if the hierarchy of posts for Hierarchical post types, and terms for Hierarchical taxonomies, is shown in the list, with some padding, and some dashes for child entries, to mimic the default listing of WP posts and terms, and in the correct order.

**Comment by jorostoyanov** [comment]
There is a lot of complications related to this request, like:

 * implementation along with the search control
 * implementation along the infinite scroll
 * visual look when not all entries are shown

And since this feature request didn't gain any popularity, I am closing the issue.

Thanks for understanding!
