### ISSUE TITLE
How to do custom field types in 2.0?

### ISSUE THREAD

**Issue by epeli** [htmlburger/carbon-fields#231]
Hi!

We need to make few custom field types within our new project. Since 2.0 release seems to be close we are considering going with it but unfortunately I'm unable to figure out what's situation with the custom field types with it. Documentation on the 2.0 branch seems to be still talking about Backbone which is gone in 2.0 if I understand correctly.

**Comment by atanas-angelov-dev** [comment]
Hi @epeli ,

We're still in the process of updating it but since we're close to release we should have more info in the coming weeks.

Here's an "in progress" field that will serve as our example once we finalize it:  
https://github.com/htmlburger/carbon-field-number

__I need to stress that this is a development version that WILL change and does not come with documentation, yet.__

**Comment by epeli** [comment]
Thanks! I managed to get it working and created couple dummy custom field types for testing.

It's an interesting idea to use Webpack DllPlugin for code/dep sharing! Since React and few other deps will come from the Carbon Fields bundle does the React version specified in my package.json matter at all now?


Could you tell what parts of the API are still in flux yet? I mean if the React component api `fields/decorators/with-setup` and data saving with the `Field_Set` stays about the same until the release it would be reasonable to start building stuff on top of it. If the integration points will change that does not really matter. They should be easy enough to update.

I known that building on top of a development version is probably not the best idea, but using the old api which is not compatible with the next version at all feels even worse. Also I would greatly prefer React over Backbone.

**Comment by vvasilev-** [comment]
Hey @epeli,

> It's an interesting idea to use Webpack DllPlugin for code/dep sharing! Since React and few other deps will come from the Carbon Fields bundle does the React version specified in my package.json matter at all now?

Yes, the version of React(and other packages) should be in the same minor range as the dependencies in Carbon Fields - e.g `15.*.*`. This is necessary because the DLL files are in `map` mode and 
the resolved paths from the JSON manifest should be available at the same location in your custom field.

> Could you tell what parts of the API are still in flux yet? I mean if the React component api fields/decorators/with-setup and data saving with the Field_Set stays about the same until the release it would be reasonable to start building stuff on top of it. If the integration points will change that does not really matter. They should be easy enough to update.

The API is pretty stable already, so you can use it safely. The biggest change that we consider is to split the `updateField` action into different meaningful actions. But this shouldn't be a problem for you since the changes to your codebase will be very small.

If you have any feedback, feel free to share it! :smiley:

**Comment by epeli** [comment]
> Yes, the version of React(and other packages) should be in the same minor range as the dependencies in Carbon Fields - e.g 15.*.*. This is necessary because the DLL files are in map mode and the resolved paths from the JSON manifest should be available at the same location in your custom field.

This situation is probably with every dependency used by CF? For example I often use recompose  which is also used by CF. If recompose where to release a new major version do I have wait for CF to upgrade to it?

> If you have any feedback, feel free to share it! 😃
 
Will do!

**Comment by vvasilev-** [comment]
> This situation is probably with every dependency used by CF? For example, I often use recompose which is also used by CF. If recompose where to release a new major version do I have to wait for CF to upgrade to it?

For the most cases, the answer is "Yes", because the new version of the package will include breaking changes/functionality/etc. that will be missing in our DLL files and this can lead to unexpected behavior of your custom field. If the new functionality is must have for your field, you can use Webpack to resolve the package from the local folder. This way the bundle of your field will become slightly bigger but you'll have the necessary functionality. 😄
