### ISSUE TITLE
Get Complex Field doesn't return types with a period.

### ISSUE THREAD

**Issue by Santana1053** [htmlburger/carbon-fields#243]
If I setup a complex field with a `.`in the type key, it displays the field properly in the browser, saves it to the database, and even re-displays the complex field with the values
![image](https://cloud.githubusercontent.com/assets/10775656/26592013/1b5107fc-4525-11e7-8cfe-8505098bdb14.png)
However when I try to get the theme options, it fails to return that key/value in the array, like it doesn't exist.

**Comment by atanas-angelov-dev** [comment]
Thanks for the report @Santana1053 .

1.x is rather liberal with what it accepts as field/group names even though not all are supported ( adding a dash to a group name is also a rather easy way to break your complex ;) ). In order to preserve backwards compatibility this will not be fixed in 1.x.
2.0 on the other hand is much stricter and allows only alphanumeric and underscore characters for names to enforce best practices and avoid issues similar to this one.
