### ISSUE TITLE
Field Map Trigger update marker

### ISSUE THREAD

**Issue by elvishp2006** [htmlburger/carbon-fields#245]
I imported some addresses into my database and would like to set the marker on the map to get the latitude and longitude, but I can only make the marker change if I change the address and perform the search, I need to update the marker just by pressing the enter or Clicking on the magnifying glass.

**Comment by elvishp2006** [comment]
I added
```javascript
this.model.trigger('change:address', this.model);
```

on ```updateAddress``` method and it work:

```javascript
updateAddress: function(event) {
	var enterKey = 13;

	if (event.type === 'keypress' && event.keyCode !== enterKey) {
		return;
	}

	var name = this.model.get('name');
	var $input = this.$(':input[name="' + name + '[address]"]');
	var address = $input.val();

	this.model.set('address', address);
	this.model.trigger('change:address', this.model);

	event.preventDefault();
},
```

**Comment by m1r0** [comment]
Hi @elvishp2006,

As I understand, you are suggesting that the field should geocode the address if there are no coordinates. The problem is that this is a special case, because you manually imported the address. In general we don't plan to support special cases like yours, because it makes the code harder to maintain.

My suggestion is that if you intend to import addresses you may as well also import the coordinates (latitude and longitude) by geocoding the addresses yourself.

This might also help: https://stackoverflow.com/questions/3807963/how-to-get-longitude-and-latitude-of-any-address
