### ISSUE TITLE
Name conflict when using identical names for containers from different types

### ISSUE THREAD

**Issue by dilirity** [htmlburger/carbon-fields#26]
When registering a post_meta container with name A and a theme_options container with the same name, an exception occurs.

**Comment by tschortsch** [comment]
All container types use the same static `$registered_panel_ids` array. I created a pull request with which you at least can use the same labels for different containers: https://github.com/htmlburger/carbon-fields/pull/25.

**Comment by atanas-angelov-dev** [comment]
Duplicate container names are now supported in cfc138259a4f0a673ff37512e3beab5703c5f062.
Ids are created based on container title (same as before) and a numerical suffix is added on duplication (merge into master is pending).

Since container classes such as "PageSettings5" are not great for styling we will soon add the ability to specify custom classes to container div elements as well.
