### ISSUE TITLE
Use the new Javascript API to initialise TinyMCE

### ISSUE THREAD

**Issue by EmilEriksen** [htmlburger/carbon-fields#260]
Version 4.8 of WP came with a new [JS API for TinyMCE](https://make.wordpress.org/core/2017/05/23/addition-of-tinymce-to-the-text-widget/). This could make the rich text field a lot cleaner and more flexible. I don't have enough experience with the JS side of Carbon Fields to refactor it myself but I'd love to see it in core!

**Comment by atanas-angelov-dev** [comment]
Thank you for the suggestion @elvishp2006 - we'll keep this in mind for future releases, however, at this time there is not much to gain to use the new API and will actually make code messier since we have to support both pre-4.8 and post-4.8 editor creation code.

We'll definitely migrate to the new API once the old usage is deprecated, though.
