### ISSUE TITLE
How can I integrate my theme?

### ISSUE THREAD

**Issue by dackr** [htmlburger/carbon-fields#273]
Please as I can integrate in my theme without composer so you can create custom fields without having to activate the plug in thanks.

**Comment by atanas-angelov-dev** [comment]
Carbon Fields 2.0 can only be installed/setup using composer at this time.

**Comment by dmhendricks** [comment]
This is what I have, if it helps anyone. I haven't used it yet in a custom theme, but I use it all the time for custom plugins that I create for clients.

```
"require": {
    "php": ">=5.3.2",
    "mnsami/composer-custom-directory-installer": "~1.1.0",
    "htmlburger/carbon-fields": "~2.0.1",
    "composer/installers": "^1.3.0"
},
"extra": {
    "installer-paths": {
        "./vendor/carbon-fields": ["htmlburger/carbon-fields"]
    }
}
```

[mnsami/composer-custom-directory-installer](https://github.com/mnsami/composer-custom-directory-installer) puts it in `./vendor/carbon-fields` rather than `./wp-content/plugins/...` or whatever. (I wish CF was _targeted_ as more of a framework than a plugin in mind - yes, I know that it is a framework by definition)

## Other Notes

### Init
Don't forget that CF 2.0 apparently requires that you `\Carbon_Fields\Carbon_Fields::boot();` now if loaded via PSR-4.

### Version Checking
If you embed CF in a plugin, you're going to want to version check CF. Say, for example, that your theme/plugin uses CF 2.0.1 but either an older version of the CF plugin loaded (for example, 1.5 or 1.6) or some other plugin has an older version embedded. WordPress will fail spectacularly when the newer classes are initialized. Then you have to rename the plugin folder because you can no longer disable it via WP Admin. That is unpleasant.

This probably has typos, and obviously some of it doesn't make sense. I just threw it together.

```
if($this->verify_dependencies(['carbon_fields' => '2.0.0'])) {
   // Execute my super-awesome plugin logic
}
```
...
```
private function verify_dependencies($deps) {
  // Check if outdated version of Carbon Fields detected
  $error = null

  if(!defined('Carbon_Fields\VERSION')) {
    $error = __( '<strong>My Plugin Name:</strong>: A fatal error occurred while trying to load dependencies.'), 'my-cool-plugin' );
    // Did you remember to run the Composer autoloader?
  } else if( version_compare( \Carbon_Fields\VERSION, $deps['carbon_fields'], '<' ) ) {
    $error = __( '<strong>My Plugin Name:</strong>: __('Danger, Will Robinson! An outdated version of Carbon Fields has been detected:' . ' ' . \Carbon_Fields\VERSION) . ' (&gt;= ' . $deps['carbon_fields'] . ' ' . __('required').') Click <a href="#some_helpful_doc_url" target="_blank">here</a> for more information.', 'my-cool-plugin' );
  }

  if($error) {
    add_action( 'admin_notices', function() {
      printf( '<div class="%1$s"><p>%2$s</p></div>', 'notice notice-error', $error );
    });
  }

  return !$error;
}
```

### Checking Into Git

If your plugin/theme is checked into git (why wouldn't be?), I usually add this so that it doesn't mess with my soul:

```
"scripts": {
    "pre-autoload-dump": [
      "find ./vendor -name '.git*' -exec rm -rf {} +"
    ]
}
```

Not ideal because Composer will complain every time you update, but if someone else has a better solution, HMU!

## Disclaimer

I am not a developer for Carbon Fields. I use it regularly, but I am also not an expert at... literally everything, so feel free to offer tweaks and advice.

_PS: THANK YOU for `set_attribute()` and `set_classes()`._

**Comment by dackr** [comment]
Thank you for your attention.

**Comment by dmhendricks** [comment]
The version checking is very important, because if you're using the latest release (2.0.1) and somebody has the old plugin from wordpress.org still installed (1.6), there will be trouble.

**Comment by dackr** [comment]
Please can you explain me with more detail on how to install because I have tried and it does not work

**Comment by dackr** [comment]
thanks for your help.

**Comment by atanas-angelov-dev** [comment]
Please follow the updated Quickstart here:
https://carbonfields.net/docs/carbon-fields-quickstart/?crb_version=2-0-0

**Comment by dmhendricks** [comment]
If you want to load it via plugin, I created a quick-and-dirty loader for 2.0.3: [Carbon Fields Loader](https://github.com/dmhendricks/carbon-fields-loader/releases)

If you want to load via Composer, you can see the `composer.json` for an example. Just delete the `./vendor` directory and run `composer install`.

**Comment by atanas-angelov-dev** [comment]
We actually released an official plugin loader as a separate package along with 2.0.3:
https://carbonfields.net/docs/carbon-fields-plugin-quickstart/?crb_version=2-0-0

**Comment by dmhendricks** [comment]
Doh! When was that released? I must have missed it. I wish I would have seen that sooner. 😄 The link is directly above New Features, too! 👅
