### ISSUE TITLE
New field type - icon

### ISSUE THREAD

**Issue by ArekZw** [htmlburger/carbon-fields#279]
Someone created addon to Carbon Fields 1.x - I used this and it's very nice. Unfortunately, it is not compatible with 2.0. Perhaps worth adding icon field to Carbon Fields 2.0?

![zrzut ekranu z 2017-07-14 15-56-51](https://user-images.githubusercontent.com/11788346/28215095-1613b0f4-68ad-11e7-945d-bb2eb40d7e7c.png)

**Comment by atanas-angelov-dev** [comment]
Hi @ArekZw ,

This is already in our internal todo list, however, it's a bit unclear when we'll have time to get to it and port it over to 2.0.

I'll keep this ticket open and update it once the field has been ported over.

**Comment by dmhendricks** [comment]
I have not tried this (I was not aware of it!), but I have been wanting this field. I'm assuming that those are Font Awesome (?) which is excellent. It would be kind of cool if we could add other icon webfonts like IcoMoon or Elegant Icons or whatever the "top 5" are. It would be really cool if one could point to a Fontello export, but I know that would probably be more work that it is worth.

It would be nice if it supported FA 5 Pro in addition to FA free. Since I have a license, I'd enjoy being able to use it. NRN, just thinking out loud again.

**Comment by filippozanardo** [comment]
Hi,
i can help if you have some code to share.
Is this the development repository?
https://bitbucket.org/htmlburger/carbon-field-icon.git

Thanks

**Comment by atanas-angelov-dev** [comment]
Icon Field 2.0.0 which works with Carbon Fields 2.x has been released:
https://github.com/htmlburger/carbon-field-icon
Simple usage docs are in the repository README.md.

To install it use:
`composer require htmlburger/carbon-field-icon`

Just an FYI: We will have a new page listing all of our extension fields on the main site soon.
