### ISSUE TITLE
Checkbox field set_option_value in 2.x

### ISSUE THREAD

**Issue by leurdo** [htmlburger/carbon-fields#285]
Hello again,
Now checkbox always returns boolean, so 
`Field::make( 'checkbox', 'crb_show_content', 'Show content' )
    ->set_option_value( 'yes' )`
has no sense. Set option is stored in db, but boolean is returned. It would be nice either to restore previous behaviour or to update docs removing this exemple.

**Comment by atanas-angelov-dev** [comment]
Whatever value you set in `set_option_value()` is the value that will be stored in the database. This can be useful if you want a custom value to be stored (e.g. you are doing some non-wp_query queries based on the value, or you just prefer to store `1` or `Y` instead of the literal `yes` etc.) but still want to have a simple boolean when getting/setting the value through the usual carbon_* functions.

It still works and has its uses (even if the ones that come to mind right now are edge-cases) so I see no reason to remove it.
