### ISSUE TITLE
Select field set_options doesn't work with numeric keys

### ISSUE THREAD

**Issue by bostondv** [htmlburger/carbon-fields#29]
When using a select field with `set_options` or `add_options` any numeric keys in the associative array are not retained in the generated select field.

Example select field:

```
Field::make('select', 'user', 'User')
    ->set_options(array(
        3 => 'John Smith',
        7 => 'Jane Doe'
    )),
```

Results in a select like this:

```
<select>
    <option value="0">John Smith</option>
    <option value="1">Jane Doe</option>
</option>
```

Expected result would be to maintain the key values whether they are a string or a number. The same behaviour is seen if using numeric string keys like `"3"` and `"7"` in the associative array.

Carbon fields v1.1

**Comment by tyxla** [comment]
Hi @bostondv,

Thanks for reporting the issue! 

We've already taken care of this issue (https://github.com/htmlburger/carbon-fields/commit/f1b7d30f9924511838e6c121e0cb7dd1b605937e), so it is fixed in the development version. 

We'll soon release a new version with the fix included. In case you use composer, feel free to use `dev-master` for the time being. In case you are using Carbon Fields as a plugin, feel free to download the development version until we release the new one.

**Comment by bostondv** [comment]
Awesome!

Btw, if I install with composer because the `composer.json` type is `library` the plugin is not getting installed to the wordpress plugin directory. I believe the standard is `wordpress-plugin` to work with [Composer Installers](https://github.com/composer/installers#current-supported-types). Perhaps should be changed?

**Comment by tyxla** [comment]
@bostondv makes sense - I've open an issue for that so we have it on record: https://github.com/htmlburger/carbon-fields/issues/31. Thanks!
