### ISSUE TITLE
carbon-fields language files german formal 

### ISSUE THREAD

**Issue by erichk4** [htmlburger/carbon-fields#292]
[carbon-fields-de_DE_formal.zip](https://github.com/htmlburger/carbon-fields/files/1177187/carbon-fields-de_DE_formal.zip)

**Comment by atanas-angelov-dev** [comment]
Thank you for the contribution @erichk4 but can you let us know what these language files bring in or improve upon?

Also can you submit these changes as a pull request instead?

**Comment by erichk4** [comment]
German has both a formal and a familiar form of “you.” Therefore Wordpress comes with 2 Versions for the german language: German (Deutsch -> de_DE) and German Formal (Deutsch (Sie) -> de_DE_formal)...

**Comment by atanas-angelov-dev** [comment]
It seems this ticket has slipped through the cracks - my apologies.

Since a number of changes have been made to the language files recently merging them by hand will be a mess.

I will be closing this ticket but we will appreciate it if you can submit a pull request based on the `development` branch with your translations.

Thanks!
