### ISSUE TITLE
The library size is too large (Carbon Fields 2.0.4)

### ISSUE THREAD

**Issue by Dimox** [htmlburger/carbon-fields#319]
The size of `carbon-fields` folder is more then 4 megabytes. I found what in the following folder total size of js files is more then 3 megabytes:

`/carbon-fields/vendor/htmlburger/carbon-fields/assets/dist/`

Is these files required? Can I delete something to reduce the end size of WordPress theme?

The size of the Carbon Fields 1.6 was significantly smaller.

**Comment by atanas-angelov-dev** [comment]
Hi @Dimox ,

The library includes minified as well as non-minified files so that when the `SCRIPT_DEBUG` constant is defined WordPress loads the non-minified ones.
In addition, the non-minified files ease development of custom fields.

You can manually delete all non-minified files in the /assets/dist/ directory if the extra size is a problem (I believe deleting the map files will also not pose a problem in production use).

**Comment by Dimox** [comment]
Okay, thank you!
