### ISSUE TITLE
Question: Best way to remove the "Actions" (Publish) box?

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-fields#341]
What is the "best" way to remove the Actions/Publish box from a CF `theme_options` page?

Out of convenience (read: laziness), I sometimes use CF to create a page that simply has an `html` field on it. It may contain documentation related to a plugin/site, but occasionally I've used it to hold some text plus a button that triggers an Ajax event. More often, I have the "docs" as a tab on the actual settings page (where the button is still relevant), but I am curious.

I'm assuming that the best way is to use CSS or JS. I thought that I would ask because of FOUC.

Thanks y'all!

![Actions Box](https://snag.gy/INyfea.jpg)

**Comment by atanas-angelov-dev** [comment]
I'd really suggest you just add your own WP admin page - it's neither hard nor time consuming and you can freely assign it as a child page to a carbon fields option page, if needed:
```php
add_submenu_page( 'some-carbon-field-options-page-file', 'Page title', 'Sub-menu title', 'manage_options', 'my-submenu-handle', function() {
    ?>
    <div>Your html here</div>
    <?php
} );
```

But if you really, really want to hack it together then css/js is the way to go - the Actions panel is directly outputted instead of rendered using React so if you use JS you can execute your code on the document ready event.

Here's the relevant template:
https://github.com/htmlburger/carbon-fields/blob/master/templates/Container/theme_options.php

**Comment by dmhendricks** [comment]
Thank you for your advice!
