### ISSUE TITLE
enable carbon fields on fronetend?

### ISSUE THREAD

**Issue by flexo911** [htmlburger/carbon-fields#357]
I want to connect to carbonfields on the frontend to be able to edit without entering adminpanel

**Comment by dmhendricks** [comment]
Is this a question or a statement?

**Comment by flexo911** [comment]
I want to create the possibility of editing the meta fields on the front of the site, more precisely so that the authors of the posts do not go into the admin panel and ruled on a special page. How to do it?
This is question

**Comment by atanas-angelov-dev** [comment]
@flexo911 this is not currently supported (I've marked the issue as a feature request for this reason)

**Comment by flexo911** [comment]
Ok. Maybe you have alternative solutions?

**Comment by batz-bar** [comment]
@flexo911, you could set the fields to be visible on the rest api,  then you could update the fields directly with a ajax call via the rest api.
Field::make(...)->set_visible_in_rest_api( $visible = true )

**Comment by its-thomas** [comment]
Being able to create custom containers / fields for WP frontend editing via Carbon Fields?

I second that! Please go for it! :+1:

**Comment by dackr** [comment]
Thanks for the great project the only thing that is missing is that all the potential of CF be used by front end

**Comment by celerart** [comment]
@its-thomas, 
in 2.2 v you can use this instruction [https://carbonfields.net/docs/advanced-topics-updating-values-2/?crb_version=2-2-0](url)

**Comment by flexo911** [comment]
@its-thomas, 
in 2.2 v you can use this instruction [https://carbonfields.net/docs/advanced-topics-updating-values-2/?crb_version=2-2-0](url)

**Comment by dackr** [comment]
Thanks is interesting to be able to update the fields but it is different that the carbon files can also be edited by front end, because you could use all your full potential, the one that can be used by front end would be a great functionality and CF be complete and would not have competitors.
Thanks is a great project.

**Comment by Elstermann** [comment]
I'm sorry, but I also have to emphasize this topic (can't hold on). Using CF straight forward at the front end definitely would be **the cherry on the cake**!

**Comment by dackr** [comment]
Well said @Elstermann we share your appreciation.

**Comment by drzraf** [comment]
**I'd like to use CBF Gutenberg integration as a form-builder toolkit in order to create frontend forms.**

But I wonder how to render a field on the frontend (outside Gutenberg)
Basically, we already have things like a React [textarea renderer](./packages/core/fields/textarea/index.js) but no way to use it, no `Field::display/render()` function.

If we would, all the rest would be straightforward.

**Comment by jorostoyanov** [comment]
Carbon Fields is meant to be used in the administration area.

There won't be an official support for using it on the frontend.

If anyone is interested, feel free to create an add-on package to support this :-)
