### ISSUE TITLE
Order posts by latest date out of items saved in complex fields

### ISSUE THREAD

**Issue by batz-bar** [htmlburger/carbon-fields#361]
I have field with complex fields that holds a list of files with dates:

```
Field::make( 'complex', 'files', 'Files' )->add_fields( array(
	Field::make( 'file', 'file', 'File' ),
	Field::make( 'date', 'file_date', 'File Date' )
) )
```

Is there a way to order posts in query based on the latest date stored in the complex field "file_date"?

Thanks for this great project!

**Comment by atanas-angelov-dev** [comment]
You can do this:
```php
$query = new WP_Query( array(
	'post_type'=>'post',
	'orderby' => 'complex_file_date',
	'order' => 'desc',
	'meta_query'=>array(
		'complex_file_date' => array(
			'key' => 'files/file_date',
			'compare' => 'EXISTS',
			'type' => 'DATE',
		),
	),
) );
```
... but there is a major caveat - it will only compare the first file_date value (or whichever MySQL chooses) found for every post (if any). This is due to how ORDER BY on a column from an INNER JOIN combined with GROUP BY behave in MySQL.

If you want to compare the latest file_date for a post to other posts' latest file_date you will have to make a custom query or apply filters to the SQL generatd by the example above to use a subquery instead of a simple table join.

---

Alternatively, you can achieve the same using minor data duplication in a hidden meta key:
1. Hook into the `'save_post'` with a priority of 11
1. Get all files stored: `$files = carbon_get_post_meta( $post_id, 'files' );`
1. Sort all file dates using php and store only the latest one: `update_post_meta( $post_id, '_latest_file_date', $latest_file_date );`
1. Use a query based on the new meta key:
	```php
	$query = new WP_Query( array(
		'post_type'=>'post',
		'orderby' => 'latest_file_date',
		'order' => 'desc',
		'meta_query'=>array(
			'latest_file_date' => array(
				'key' => '_latest_file_date',
				'compare' => 'EXISTS',
				'type' => 'DATE',
			),
		),
	) );
	```

If you have previously created posts you will have to create a migration script so they get their new `_latest_file_date` meta or they will not be present in the query results until someone edits the posts (so the `'save_post'` action is called). If you only have a handful of posts then manually going through them and clicking "save" is the simpler approach : )

---

I'm sure there are other ways to achieve this as well but these are the ones that come to mind right now.

**Comment by batz-bar** [comment]
Thanks!
The second solution is perfect.
