### ISSUE TITLE
Please add babel-polyfill

### ISSUE THREAD

**Issue by jackreichert** [htmlburger/carbon-fields#369]
I’d like to be able to use this to support people using older browsers. I know you don’t specifically support that, but if you could please add babel-polyfill it would make it work for many more people.

I added it as a dependency in the loader and it solved every one of the compatibility issues I was having.

Thanks.

**Comment by vvasilev-** [comment]
Hey, @jackreichert

Can you tell us on which browsers/platforms do you have problems? We used `babel-polyfill` in the past but we ran into conflicts with plugins like Yoast SEO because they're using the same polyfill. Also, you can check #368 if you have problems with old IEs.

**Comment by jackreichert** [comment]
I was testing it in IE11. We’re not using Yoast SEO, but I can see if my solution conflicted.

What I did to resolve my issues was to enqueue babel-polyfill from the CDN, and have it as a dependency for cf-core-js.

**Comment by vvasilev-** [comment]
The [fixes ](https://github.com/htmlburger/carbon-fields/commit/daefc1e060b06568c5ef5b3c67159e25298718f7)for IE are in our development branch so they will be released soon. Regarding `babel-polyfill`, we won't add it back because we don't want any further conflicts with other plugins that are using the polyfill. Although, if you still have a problem in some old browser feel free to open an issue and we'll be happy to fix it.

**Comment by jackreichert** [comment]
Thank you!
