### ISSUE TITLE
Comment Meta not working

### ISSUE THREAD

**Issue by kurogane1988** [htmlburger/carbon-fields#372]
Hello

I'm using carbonfields to create meta for comments. I followed to this instruction https://carbonfields.net/docs/containers-comment-meta/?crb_version=2-1-0 but when I access to edit comment in dashboard, I only see the container name "Comment Information" but i can't find the field "Comment Rating" and "Additional Comment Information"

**Comment by atanas-angelov-dev** [comment]
Hi @kurogane1988 ,

I just tested our example code on a fresh setup using the latest release (2.1.0) and the fields work correctly.
Can you please make sure you have followed the quickstart (or plugin quickstart) docs page steps (https://carbonfields.net/docs/carbon-fields-quickstart/?crb_version=2-1-0) ?

Also please make sure you are using a full release instead of any git branch such as `master` - releases contain all distribution files in comparison to branches where you have to run the build process manually.

**Comment by kurogane1988** [comment]
Hi @atanas-angelov-dev 

After I run composer update carbonfields from version 2.0.4 to version 2.1.0, It worked. 

Thanks for support.

**Comment by atanas-angelov-dev** [comment]
👍
