### ISSUE TITLE
Updating Theme Settings Complex Field via code

### ISSUE THREAD

**Issue by BenBroide** [htmlburger/carbon-fields#385]
To update post meta with a custom fields, we use
` carbon_set_post_meta( 10, 'crb_complex', $array );`

How we update theme options fields with a complex custom field? I didn't find an example in the docs.

Thanks

**Comment by emohamed** [comment]
You could use `carbon_set_theme_option`

https://github.com/htmlburger/carbon-fields/blob/master/core/functions.php#L48

**Comment by BenBroide** [comment]
If iv'e set up a field 
`Container::make( 'theme_options', 'Redirection' ).........`
How do I retrieve it? What is the name and what is the container ID?

**Comment by BenBroide** [comment]
Example of code for the theme options I'm trying to get:

```
Container::make( 'theme_options', 'Redirection' )->set_page_parent( 'options-general.php' )
         ->add_fields( [
	         Field::make( 'complex', 'redirects' )
	              ->add_fields( 'redirect', [
			              Field::make( 'text', 'table' )->set_width(20),
			              Field::make( 'text', 'id' )->set_width(5)
                 ])
        ]);
```

**Comment by atanas-angelov-dev** [comment]
Hi @BenBroide ,

When fetching values you normally only need the field name (you need the container id only if you have duplicate field names between containers of the same type).

In your case to get the `redirects` field values you would call this:
```php
$redirects = carbon_get_theme_option( 'redirects' );
print_r( $redirects );
```

PS:
A good practice is to always prefix field names (e.g. `crb_redirects`) in order to avoid collisions with WordPress or plugin meta/option names.

**Comment by BenBroide** [comment]
@atanas-angelov-dev Thanks!
