### ISSUE TITLE
Migration, ACF  to CRF

### ISSUE THREAD

**Issue by jquimera** [htmlburger/carbon-fields#419]
I'm migrating a theme that used ACF to the CRF. But I have a problem.The fields are not showing the default value, but only fields ids.

```

<h1 style="color: red">Sidebar Position: <?php echo carbon_get_term_meta($term_id,'my_sidebar');?></h1>
<h1>Custom Sidebar: <?php echo carbon_get_term_meta($term_id,'custom_sidebar');?></h1>
<h1>Pagination: <?php echo carbon_get_term_meta($term_id,'pagination');?></h1>
<h1>Color: <?php echo carbon_get_term_meta($term_id, 'custom_color');?></h1>
<h1>Background Color: <?php echo carbon_get_term_meta($term_id, 'custom_background');?></h1>
<h1>Background Image: <?php echo carbon_get_term_meta($term_id, 'custom_background_image');?></h1>
```

print result:

Sidebar Position: field_w49pfz4v5d0f3
Custom Sidebar: field_fc1u67847d0pd
Pagination: field_eb2d4bc6cfu3n
Color: field_c1u6b8d0prfa6
Background Color: field_a1u5bprta18d0
Background Image: field_0ej2y5u2a3e2q

What's going on? Thanks.

**Comment by atanas-angelov-dev** [comment]
Hi @jquimera ,

In your case the meta keys used by ACF and CF match so CF pulls whatever data ACF has stored in these meta keys. Since ACF stores field IDs in these meta keys - CF pulls those ACF field IDs.

Here's an example of what is stored for a field named "Test" in ACF:

| meta_id | post_id | meta_key | meta_value          |
|---------|---------|----------|---------------------|
| 101     | 47      | _test    | field_5a0d8b8590763 |
| 100     | 47      | test     | 12345               |

You can see that the underscore version of the meta holds the field ID and since Carbon Fields adds an underscore (to mark the meta as hidden from the edit screen per WordPress' functionality) the field ID ends up being pulled for the field.

In order to pull the actual value you will need to create a migration script to switch the meta values for the underscore-version of the meta or just switch them out manually if you only have a few.
Also be careful with how the meta value is formatted - ACF and Carbon Fields have different formats of storing data (CF uses plain data with special keys depending on the field type while ACF may use multiple identical keys or serialized data for more complex fields - if you are writing a migration script you should use the `carbon_set_*()` functions to ensure proper key/value formatting for Carbon Fields).

We are exploring solutions for automatic ACF -> Carbon Fields migrations, however, there is no solution available right now.

**Comment by jquimera** [comment]
@atanas-angelov-dev, 

I understand, I changed the name of the fields, that solved. Thanks.
