### ISSUE TITLE
Better code comment for Field->set_name($name) method

### ISSUE THREAD

**Issue by mindfullsilence** [htmlburger/carbon-fields#451]
## Version

  - Carbon Fields: v1.6

## Expected Behavior
An explanation or `@see` link to more information to the `set_name()` method of the `Field` class

## Actual Behavior
I'm currently working on a pretty involved theming system that heavily relies on Carbon Fields. Currently, the code documentation of the [set_name method](https://github.com/htmlburger/carbon-fields/blob/v1.6/core/Field/Field.php#L409) states to `Use only if you are completely aware of what you are doing.`. What are the implications of using this method? The warning is clear in its intent, but extremely ambiguous in its explanation.

**Comment by atanas-angelov-dev** [comment]
Hi @mindfullsilence ,

Note that v1.6 is not supported anymore (with the exception of critical security issues, of course).

AFAIK, the method was used for several critical purposes (meta key generation, then modified for input name attribute, some voodoo to work with Complex fields etc.) which require intimate knowledge of how the plugin worked which is why that comment exists. There is no documentation on the subject and I don't really recommend using it directly.

**Comment by mindfullsilence** [comment]
Thanks @atanas-angelov-dev 
As far as version number, I just picked one for reference. v2.1.1 also has the [same comment](https://github.com/htmlburger/carbon-fields/blob/2.1.1/core/Field/Field.php#L639)

Appreciate the explanation. Helps a lot.
