### ISSUE TITLE
[Help Wanted] Improve documentation

### ISSUE THREAD

**Issue by GaelleHenaf** [htmlburger/carbon-fields#454]
Hello, 

Just an idea for you ! :)

I found that screen captures is missing in your documentation.

To know if we use the plugin in the right way it's necessary to test him but with capture the process will be easier for dev.

**Comment by BenBroide** [comment]
You could fork the docs, add screenshots and send a pull request

**Comment by zavaremre** [comment]
+1

**Comment by kuvu** [comment]
+1 on the documentation.

I find that examples for multiple scenarios are lacking. Ie; how to create a container on two or three post types ...

**Comment by Xilonz** [comment]
How can we do this? I'd like to help.

I would like to see how to use complex fields/association fields in, for example, a wp_query.

**Comment by BenBroide** [comment]
I would like to share 2 ideas I have that may improve the docs examples.

1. Maybe we could add a section under each page in docs "code examples" that would have more code examples beyond the basic code example , and users could send PR with more extended code examples
2. This is a more complex idea:
Set a test box In a similar way that some plugins/themes allow users to access a demo box to test and feel the product on a live wp site. 
So there will be a "examples repo" which would be set on the demo box, and users would be able to login and see how the code in the repo functions and feel. We could set a wp cron job to reset the box data every n minutes to avoid testing data piling up.

**Comment by dmhendricks** [comment]
(anyone: please correct any of this if it is wrong)

@Xilonz - The doc repo is [htmlburger/carbon-fields-docs](https://github.com/htmlburger/carbon-fields-docs). You can fork the repo, clone it, make changes, push the changes to your fork, and then do a pull request (PR).

**Note:** If you're going to change multiple/unrelated areas of the docs, you'll probably want to branch  them into separate PRs - it makes it easier to merge specific portions and make change comments on them (in my observation - I am not an expert). If you dump one huge change request that contains changes to a lot of different areas of the docs, it reduces the likelihood that it will be accepted because it makes it more difficult to sift through/propose modifications for.

If it is a small change or related to one specific page/feature, you probably don't have to branch (but you may wish to anyway so it doesn't block you on other/future changes that you may submit).

If some/all of this doesn't make sense or doesn't answer your question, feel free to ask. As mentioned, **I am not an expert**, but many folks here are. There may be a more appropriate methodology/workflow.

**Comment by jorostoyanov** [comment]
Please post any further ideas and PRs regarding the docs in its repo - https://github.com/htmlburger/carbon-fields-docs

Closing this ticket!
