### ISSUE TITLE
Extending Fields: rendering field's template without React

### ISSUE THREAD

**Issue by wujekbogdan** [htmlburger/carbon-fields#460]
I'm looking at the [carbon-field-number](https://github.com/htmlburger/carbon-field-number) example. The PHP part is clear to me, but I'm confused a little about the JS part.

I see that you use React to render the field's template. But what If I wanted to use a different JS library: Vue.js, Angular... or even plain JS?

I don't really understand based on what the PHP code "guess" what JS code is responsible for rendering a field... or the opposite: How the JS script "knows" where to render? 

I didn't find any information in the [JS API documentation](https://carbonfields.net/docs/advanced-topics-javascript-api/?crb_version=2-1-0) how to wire up the JS code to a specific Field. I guess that a JS module must expose some public API and/or there must be some naming convention that I have to use in order to "tell" PHP that "this JS module is responsible for rendering this carbon field".

---
**// edit**

I found that the [bootstrap.js](https://github.com/htmlburger/carbon-field-number/blob/master/assets/js/bootstrap.js) is the entry point and it imports the `registerFieldComponent` from `lib/registry`. But what the `lib/registry` module is? I can't find such a module either in the `package.json` nor in the repository.

...I must have missed something that's really trivial.

**// edit 2**
OK. It seems more clear now when I found this line in the Webpack config:

``` javascript
/**
 * This path assumes that Carbon Fields and the current template
 * are both in the `/plugins` directory. Change if according to your needs.
 */
const root = path.resolve(__dirname, '../carbon-fields');
```

the `registerFieldComponent` is meant to be loaded from the carbon fields plugin directory and it seems that we're forced to use React because the `registerFieldComponent` depends on React. 

Correct me if I'm wrong.

**Comment by atanas-angelov-dev** [comment]
Hi @wujekbogdan ,

Yes, React is required in order to build your own fields.

Looking at the snippet you added - are you sure you are using the latest field template? The latest one is at https://github.com/htmlburger/carbon-field-template which includes a step-by-step readme on how to create your first field.

**Comment by wujekbogdan** [comment]
@atanas-angelov-dev 

> Looking at the snippet you added - are you sure you are using the latest field template? 

I was using [carbon-field-number](https://github.com/htmlburger/carbon-field-number) which is nearly the same and indeed I missed the template's readme note about Webpack paths. 

---
It would be great if Carbon fields wasn't so tightly coupled with React. React is great, but IMO it shouldn't be required. It would be much better if there was some framework agnostic API that any framework (or even pure JS) could use. Or maybe there is some API but it's not documented?

Dos such change required a lot of under-the-hood changes?

**Comment by vvasilev-** [comment]
> It would be great if Carbon fields wasn't so tightly coupled with React. React is great, but IMO it shouldn't be required. It would be much better if there was some framework agnostic API that any framework (or even pure JS) could use. Or maybe there is some API but it's not documented?
> Dos such change required a lot of under-the-hood changes?

Hi @wujekbogdan,

The [JS API](https://carbonfields.net/docs/advanced-topics-javascript-api/?crb_version=2-1-0) isn't intended to create a new field, it's a simple wrapper around the underlying structure of Carbon Fields. The framework-agnostic API will require a complete rewrite of Carbon Fields which we don't plan for now because most JS frameworks don't share a unified interface for building components. 

If you have any other questions about writing a custom field, feel free to ping me. 😄

**Comment by wujekbogdan** [comment]
@vvasilev- 
Everything is clear now, thanks for your time.
