### ISSUE TITLE
New field type: Button

### ISSUE THREAD

**Issue by Xilonz** [htmlburger/carbon-fields#461]
It would be nice to have an button that can execute functions.
I can, of course, just use the html field and set an post or get parameter, but it would be a nice addition to CF.

Example:
```
Field::make( 'button', 'my_button_id')
   ->set_alert( 'Are you sure? This will reset your menu items and something else')
   ->set_action( function() { create_theme_example_posts() });
```

**Comment by dmhendricks** [comment]
I think that I had mentioned this in the past but cannot find the post. Of course, you can do anything with JavaScript already, but this was what I had envisioned as the model: [AJAX Button](http://www.titanframework.net/docs/ajax-button/)

**Comment by atanas-angelov-dev** [comment]
A button is not really a field - it does not have a value and it executes arbitrary code instead of storing a value.

At this time there are no plans to implement this but feel free to write your own - you can even distribute it as a composer package that extends Carbon Fields (https://github.com/htmlburger/carbon-field-template)
