### ISSUE TITLE
Assotiation field from complex field

### ISSUE THREAD

**Issue by Koxae** [htmlburger/carbon-fields#463]
## Version

  - Carbon Fields: last
  - WordPress: last
  - PHP:

## Expected Behavior
It is necessary to display the data from the post, added to the field "association", which is located in the field "complex"

## Actual Behavior
I can not create the correct query. Therefore, the post data from the assotiation field is not output.

## Container definition
```php
if ( has_post_format('aside') ) :  \\ condition for the format of posts
$places = carbon_get_post_meta( $post->ID, 'event_options' ); \\ the beginning from the complex field
if ( $places ) { foreach ( $places as $place ) {
echo $place['event_date'];
echo $place['event_time'];

$adress = carbon_get_post_meta( $post->ID, $place['event_adress'] ); \\ association field, my amateur performance. does not work
foreach ( $adress as $item ) {
echo carbon_get_post_meta($item['id'], 'venue_adress');
}

}
}
endif;
```
## Comments
Help me, please.

**Comment by Xilonz** [comment]
The documentation can use some examples on receiving complex fields in my opinion.

Did you do a var_dump on ```$place```? What value's are available?
Also, are you sure you set up ```event_adress``` instead of ```event_address````?

Read this: https://carbonfields.net/docs/complex-field-nested-complex-fields/?crb_version=2-1-0
And this: https://carbonfields.net/docs/advanced-topics-field-name-patterns/?crb_version=2-1-0
The association field acts somewhat like a complex field.

I'm not sure this is correct:
```php
if ( has_post_format('aside') ) :  \\ condition for the format of posts
    $places = carbon_get_post_meta( $post->ID, 'event_options' ); \\ the beginning from the complex field
    if ( $places ) {
        foreach ( $places as $i => $place ) {

            echo $place['event_date'];
            echo $place['event_time'];

            $adress = carbon_get_post_meta( $post->ID, 'event_options['.$i.'][event_adress]' );
            foreach ( $adress as $item ) {
                echo carbon_get_post_meta($item['id'], 'venue_adress');
            }

        }
    }
endif;
```

**Comment by atanas-angelov-dev** [comment]
Closing due to lack of response from OP.
