### ISSUE TITLE
Question: conditional add attribute

### ISSUE THREAD

**Issue by BenBroide** [htmlburger/carbon-fields#468]
## Version

  - Carbon Fields: latest
  - WordPress: latest
  - PHP: latest

## Expected Behavior
Is there any option to add an attribute by condition? 
Example: adding "readOnly" by role.

Thanks

**Comment by atanas-angelov-dev** [comment]
Conditions specificaly for field attributes are not supported.

You could still write your own if() check though:
```php
$field = Field::make( ... );
if (!current_user_can()) {
	$field->set_attribute( ... );
}

Container::make()
	->add_fields( array(
		...
		$field,
		...
	) )
```

PS:
When creating tickets in the future, please specify exact versions instead of `latest`. Latest can be the latest stable, the latest beta or a manually built latest version from `master` (this also applies partially to PHP and WordPress).

**Comment by BenBroide** [comment]
Thanks! this answered my question.
