### ISSUE TITLE
Translate default fields label

### ISSUE THREAD

**Issue by BenBroide** [htmlburger/carbon-fields#471]
## Version

  - Carbon Fields: 2.1 DEV
  - WordPress: 4.9.4
  - PHP: 5.5.9

## Expected Behavior
When no custom label name is set Default fields names should be able to have a translation same way all other strings in the plugin has.

## Actual Behavior
The Default fields labels are showing up in English 
![hebrew default fields name](https://user-images.githubusercontent.com/11011901/36602571-5a29dc4e-1886-11e8-9b7d-f0c682be587b.png)
creenshot attached. 

## Container definition
```php 
Container::make( 'post_meta', 'Custom Data' )
    ->where( 'post_type', '=', 'page' )
    ->add_fields( array(
        Field::make( 'map', 'crb_location' )
            ->set_position( 37.423156, -122.084917, 14 ),
        Field::make( 'sidebar', 'crb_custom_sidebar' ),
        Field::make( 'image', 'crb_photo' ),
        Field::make( 'rich_text', 'crb_rich_text' ),
    ));
}
```

## Steps to Reproduce the Problem

  1. setup installation  with fields in Hebrew with the fields above

## Comments
How could we set the default labels translation?
This issue example in Hebrew, but I think it's relevant to all languages. 
Thanks!

**Comment by atanas-angelov-dev** [comment]
Hi @BenBroide ,

AFAIK translating entire dynamically generated strings is an antipattern (e.g. they cannot be detected by language tools which statically analyze your files).

Translating strings should be a conscious and deliberate effort so I suggest you manually add translated labels instead of relying on automated label guessing and translation.
