### ISSUE TITLE
Theme Options | load default settings button ? 

### ISSUE THREAD

**Issue by zavaremre** [htmlburger/carbon-fields#489]
## Version

  - Carbon Fields:2.2.0
  - WordPress:4.9.4 
  - PHP:

 the default settings   button
![image](https://user-images.githubusercontent.com/35058780/37797660-7e54e0b8-2e2b-11e8-89fa-e7ed285819ef.png)

## Comments
_Please add any other comments here_

**Comment by breath-ee** [comment]
That's a good idea! 😃

**Comment by jorostoyanov** [comment]
Carbon Fields provides the `set_default_value` method which you can use for this purpose.

Adding a button to "Reset" or "Load Default Values" should be considered as an add-on, instead of bundling it as a core feature.

Feel free to write an add-on package which adds this functionality :-)

Thanks!
