### ISSUE TITLE
carbon field slow loading

### ISSUE THREAD

**Issue by dackr** [htmlburger/carbon-fields#506]
## Version

  - Carbon Fields: 2.2.0
  - WordPress: 4.9.5
  - PHP: 7.2.1

Created with coal fields and is delaying loading the wordpress administrator page I have several fields association, selects, rich_text, conditional fields. please help me improve the administrator's load.

Thanks For your help.

**Comment by deqngeorgiev** [comment]
Hi @dackr ,

Can you provide more details about your setup and what you want to achieve, please?

**Comment by dackr** [comment]
Hellos this is result of configuration.

admin
![_carbon-fields](https://user-images.githubusercontent.com/1920588/38873335-1e38583c-421b-11e8-9813-137efd613451.jpg)
code

![captura de pantalla 2018-04-17 a la s 08 43 04](https://user-images.githubusercontent.com/1920588/38873927-8a084562-421c-11e8-99d9-59ee7aed0c99.png)
![captura de pantalla 2018-04-17 a la s 08 42 52](https://user-images.githubusercontent.com/1920588/38873928-8a24dd4e-421c-11e8-91c3-c0f8242702f0.png)
![captura de pantalla 2018-04-17 a la s 08 42 41](https://user-images.githubusercontent.com/1920588/38873929-8a478934-421c-11e8-8907-f97fc9aa8c4f.png)
![captura de pantalla 2018-04-17 a la s 08 42 32](https://user-images.githubusercontent.com/1920588/38873931-8a6b57e2-421c-11e8-95e9-7083c38c13e3.png)
![captura de pantalla 2018-04-17 a la s 08 42 24](https://user-images.githubusercontent.com/1920588/38873932-8aa5f5fa-421c-11e8-9bb7-b75a623a85ef.png)
![captura de pantalla 2018-04-17 a la s 08 42 13](https://user-images.githubusercontent.com/1920588/38873933-8ac6a3cc-421c-11e8-856e-65239060581a.png)

please help me thanks.

**Comment by deqngeorgiev** [comment]
Can you try to remove almost all values from the `select` and see if there is an improvement in the performance?

**Comment by dackr** [comment]
I have eliminated the select but it is almost the same does not improve the performance.

**Comment by deqngeorgiev** [comment]
Since I can not reproduce your case because I do not know what you have in your database (posts, users, comments, taxonomies), can you try something else, please? I think getting all posts, pages, products, users, comments and etc. may cause the problem, so can you try to remove the association fields and check the performance?

**Comment by dackr** [comment]
I have removed the associative fields and it has improved a bit but the same slow load also I have removed the conditional so that it appears only in the home I improve a little more but not much is slow.
Thank you for your help.

**Comment by deqngeorgiev** [comment]
If you've removed all of the association fields and the large select field and there are still issues with the performance I think the problem is not with the Carbon Fields. There are not a lot of fields remaining and I don't see a field which can cause the problems. You can try to disable other plugins and check the performance.

**Comment by dackr** [comment]
if it were the case of the associative fields that I would have to do to improve it, please, I have associative fields within complex fields organized by tab, the question is how could I improve their performance by looking in post, pages, categories , tags each associative field.
please if you could give me an example code.
thanks for your help.

**Comment by deqngeorgiev** [comment]
In my opinion, you should change your design. You are getting a lot of data (posts, pages, users, comments, terms, etc.)  for every entry in the complex fields and there are a lot of queries to the database which affect the performance. Since you are using these fields for links you can make a custom query/queries to get all of the items one time, add them to an array and use a select field with that array, for example.

**Comment by dackr** [comment]
Please have an example to see how to do that from carbon field ?.
thanks for your help.

**Comment by BenBroide** [comment]
Separate whatever you can to different post types, after all these are wp custom fields, not a nosql database

**Comment by m1r0** [comment]
@dackr, sorry for the late reply, but could you provide a gist with all the fields definitions (custom-fields.php), so I can test the loading speed?

**Comment by dackr** [comment]
@m1r0 Please Can you send your mail to send the file? or if you want access by ftp and user

**Comment by m1r0** [comment]
@dackr You can just paste the file's content in a gist (https://gist.github.com/) or any other text/code sharing service and share the link here.

**Comment by dackr** [comment]
Thanks for four help this is link.
[https://gist.github.com/dackr/a39542a089223669a249b98926f00f03](url)

**Comment by dackr** [comment]
Thanks for your help this is link
[https://gist.github.com/dackr/a39542a089223669a249b98926f00f03](url)

**Comment by dackr** [comment]
thanks for your help this is link
https://gist.github.com/dackr/a39542a089223669a249b98926f00f03

**Comment by m1r0** [comment]
Thanks @dackr,

I think that your issue is related to the association field performance problem. If there are many relations/entries - you get a performance hit. This is a known issue. Feel free to continue the conversation here https://github.com/htmlburger/carbon-fields/issues/318.
