### ISSUE TITLE
Strange situation with ->set_page_parent($basic_options_container)

### ISSUE THREAD

**Issue by Roman52** [htmlburger/carbon-fields#529]
## Version
  - Carbon Fields: 2.2.0
  - WordPress:  4.9.5
  - PHP: 5.6

[Here is the video of my problem.](https://www.youtube.com/watch?v=7wmYR9mC2z0)

Here is my code:

`use Carbon_Fields\Container;
use Carbon_Fields\Field;

// Theme options
$basic_options_container = Container::make('theme_options', 'Настройки темы') 
	->set_icon('dashicons-carrot')
	->add_fields( [
		Field::make('text', 'rz_page_home_title', 'Заголовок для описания главной страницы'),
	] );

// Author
Container::make('theme_options', 'Информация об эксперте')
	->set_page_parent($basic_options_container)
	->add_fields( [
        Field::make('rich_text', 'rz_main_author_descr', 'Текст'),
	] );

// soc
Container::make('theme_options', 'Социальные сети')
	->set_page_parent($basic_options_container)
	->add_fields( [
		Field::make('text', 'social_vk', 'Вконтакте'),
	] );`

**Comment by deqngeorgiev** [comment]
Hi @Roman52,

Thank you for the feedback!

I've checked your case and the problem is that you've used Cyrillic names for the containers without passing an ID for the container. In that case, Carbon Fields automatically creates unique ID for each container from the container name but the container ID can't contain Cyrillic symbols and they are automatically trimmed which causes the issues. 

You should pass an IDs as the second parameter to your containers and everything will work fine.

Example:

```
$basic_options_container = Container::make('theme_options', 'theme_settings', 'Настройки темы')
	->set_icon('dashicons-carrot')
	->add_fields( [
		Field::make('text', 'rz_page_home_title', 'Заголовок для описания главной страницы'),
	] );
// Author
Container::make('theme_options', 'expert_information', Информация об эксперте')
	->set_page_parent($basic_options_container)
	->add_fields( [
		Field::make('rich_text', 'rz_main_author_descr', 'Текст'),
	] );

// soc
Container::make('theme_options', 'social_networks', 'Социальные сети')
	->set_page_parent($basic_options_container)
	->add_fields( [
		Field::make('text', 'social_vk', 'Вконтакте'),
	] );`
```

**Comment by Roman52** [comment]
Thank you so much for your answer!
