### ISSUE TITLE
Is there any way that I can save the option data to a custom database table?

### ISSUE THREAD

**Issue by iwillhappy1314** [htmlburger/carbon-fields#548]
I want to save the option data that build with Carbon Field to a custom database table, I have viewed the documentation  [Serialized Datastore](https://carbonfields.net/docs/guides-serialized-datastore/?crb_version=2-2-0), and then noticed that is not what i wanted?

like https://github.com/liquidweb/woocommerce-custom-orders-table?

**Comment by emohamed** [comment]
Hi @iwillhappy1314 

This is certainly possible. You should use https://github.com/htmlburger/carbon-fields/blob/master/core/Datastore/Theme_Options_Datastore.php as a reference -- basically, you'd need to implement CRUD methods so they use your table instead of wp options, and then setup your fields to use that datastore like this:

```
Field::make( 'complex', 'crb_custom_datastore_complex' )
    ->set_datastore( new MyDatastore() )
    ->add_fields( array(
        Field::make( 'text', 'text' ),
    ) ),
Field::make( 'map', 'crb_custom_datastore_map' )
    ->set_datastore( new MyDatastore() ),
``` 

Hope that this helps. Happy coding!

**Comment by iwillhappy1314** [comment]
Thanks a lot! @emohamed
