### ISSUE TITLE
Is there any way I can do custom fields to be edited from the front end by the user?

### ISSUE THREAD

**Issue by dackr** [htmlburger/carbon-fields#552]
I want to make a website for the user to fill out his work notice.
it is possible to do some of this with this excellent plugin thanks for your answers

**Comment by vvasilev-** [comment]
Hi @dackr,

Currently, that isn't supported because the library is designed to be used only in the admin area of WordPress. You can create a custom UI in your frontend that uses the REST API of WordPress to save the changes in the backend.

Please keep in mind that the issues are used only for bugs/feature requests/etc. If you need some assistance or have another question you can start a new discussion in StackOverflow with the following tags `php wordpress carbon-fields`.
