### ISSUE TITLE
Change the field prefix? (migration from ACF)

### ISSUE THREAD

**Issue by Yakoogle** [htmlburger/carbon-fields#568]
Have the CF the way to redefine default '_' prefix? We are running our project with ACF now, and have much content, so we just want to use old names without prefixes.

Or maybe there is a way of migration from ACF to CF?

**Comment by vincentjflorio** [comment]
I had a similar question, because we're trying to make our fields visible to Elementor. I tried even using Toolset's free version to "take ownership" of my Carbon Field but it can't see it to begin with to take ownership of it.

I visited your link but in the example get_key_for_field looks like it's retrieving values by looking for an existing format, the default setup where the underscore already exists, and I don't see one being introduced in the saving function.

So, I decided to try it anyway and see what it does (that maybe the example is an example _of_ clipping off the underscore, but when I tried it I got:

Class 'Carbon_Fields\Datastore' not found

despite declaring the "use" statement at the top of my functions.php file. Is it an issue because I am using the plugin form of the newest version 3?

**Comment by dmhendricks** [comment]
I use the serialize datastore example for some applications (not for your situation, but for complex fields). If it helps, here is a code sample. I always use Composer, so this probably contains errors because it is off the top of my head.

1. Load Carbon Fields.
```php
require_once 'path/to/core/Carbon_Fields.php';
```
2. I give my serialized datastore a namespace. Ex: [Serialized_Theme_Options_Datastore.php](https://github.com/dmhendricks/wordpress-base-plugin/blob/master/app/Datastores/Serialized_Theme_Options_Datastore.php)
3. I autoload the class using [PSR-4](https://github.com/dmhendricks/wordpress-base-plugin/blob/master/composer.json), but you can load it manually:
```php
require_once 'path/to/Serialized_Theme_Options_Datastore.php`;
```
4. Initialize Carbon Fields
```php
add_action( 'after_setup_theme', array( 'Carbon_Fields\\Carbon_Fields', 'boot' ) );
```
5. Create your fields ([example](https://github.com/dmhendricks/wordpress-base-plugin/blob/master/app/Settings/Settings_Page.php)).
```php
<?php
// ...
use Carbon_Fields\Datastore\Datastore\Serialized_Theme_Options_Datastore;

add_action( 'carbon_fields_fields_registered', 'some_callback'  );

function some_callback() {
    Field::make( 'complex', 'crb_custom_datastore_complex' )
        ->set_datastore( new Serialized_Theme_Options_Datastore() )
        // ...
}
```

Like I said, this probably contains errors, but I hope it helps.

**Comment by vincentjflorio** [comment]
It definitely gives me a lead at least. I very much am grateful for you taking the time to provide that reference. I'll chew on that and see where it takes me and report back if I have any success that could be useful to anyone else. Much obliged!

**Comment by martisj** [comment]
@Yakoogle did you figure out how to do this?

**Comment by SteeveOCBo** [comment]
Hi there !

I think i had the same issue, and i found this with the 3.6.3 version of Carbon Fields :

You should remove the `_` (underscore) in 2 files  : 

In the file **\vendor\htmlburger\carbon-fields\core\Field\Field.php line 85**
`protected $name_prefix = '_';` 

And the file **\vendor\htmlburger\carbon-fields\core\Toolset\Key_Toolset.php line 24**
`const KEY_PREFIX = '_';`

It's work for me, let me know if it work for you too..
