### ISSUE TITLE
Question/Feature Request: Storing sensitive data

### ISSUE THREAD

**Issue by mitchellknight** [htmlburger/carbon-fields#583]
Does Carbon Fields have a way to store sensitive data in a format that is encrypted at rest? It might be a useful feature for a future release.

**Comment by deqngeorgiev** [comment]
Hi @mitchellknight,

Can you provide more details about the use case, please? I think this would be a specific case and such feature wouldn't be useful in the core. You can create a custom Datastore (https://carbonfields.net/docs/guides-serialized-datastore/?crb_version=2-2-0) and encrypt your information before saving it to the database.

I'm closing this in order to organize our issues but I am open to continue with the discussion if you have something in mind :)

**Comment by mitchellknight** [comment]
I was looking in to using Carbon Fields to build a simple Project Management plugin for self-hosted WordPress sites. It's possible sensitive information (such as passwords for 3rd-party services) would be shared between users that have logged in. To provide a basic level of security I would like to have the option to optionally encrypt some fields in the database.
