### ISSUE TITLE
Upgrading to 3.0

### ISSUE THREAD

**Issue by adamromanowski** [htmlburger/carbon-fields#629]
Hello!

Congrats on v3.0. Looks really impressive!

However, are you guys planning on putting together and upgrade guide just like in previous releases.

Thanks!

**Comment by ggeorgiev96** [comment]
Hi @adamromanowski!

We are glad you are enjoying our new release!

As v3.0 does not introduce any breaking changes to the base functionality, no upgrade guide is needed. 

We are currently working on upgrading our extendibility guide which will be released soon.

**Comment by davejtoews** [comment]
@ggeorgiev96 is this extendibility guide still in the works and will it include instructions for upgrading 2.x extensions to be 3.x compatible? Hoping to upgrade to 3.0 in order to get post revisions, but this breaks my custom extensions.

**Comment by davejtoews** [comment]
As it turns out, more than just my extensions seem to be broken. I can't get Carbon Fields 3 to play well with my page editor unless I use Gutenberg. Which is a problem for me, as I don't want Gutenberg. CF3 seems to be overwriting the global js variable `_` with lodash, and breaking wp-core scripts that expect it to be underscores.
