### ISSUE TITLE
Reduce a plugin size

### ISSUE THREAD

**Issue by Roman52** [htmlburger/carbon-fields#652]
Carbon Fields: 3.0.2

The size of carbon-fields is 8.6 megabytes. Can I delete some files to reduce the size? 
I am not going to use a debug and use non-minified files.

Could you tell me please what files can I delete? 
Thank you for your work and a great plugin!

**Comment by emohamed** [comment]
Hi @Roman52 

You can delete the following files:

 * build/classic/core.js(1.2M)
 * build/classic/vendor.js(1.8M)
 * build/classic/metaboxes.js(255K)
 * build/gutenberg/core.js(1.2M)
 * build/gutenberg/vendor.js(111K)
 * build/gutenberg/blocks.js(158K)
 * build/gutenberg/metaboxes.js(252K)

This should reduce the size with about 5MB.

Carbon Fields is shipping with these files in order to allow using of `SCRIPT_DEBUG`.

**Comment by pablo-sg-pacheco** [comment]
Hello, 

I noticed that if you download the zip file from:
https://github.com/htmlburger/carbon-fields/archive/development.zip
The final size is small (484kb).

So, besides deleting the files you mentioned is it possible to do something else to reduce the final size even more? 

Maybe we could add something to .gitignore? Maybe the whole build folder? I don't know

**Comment by atwellpub** [comment]
Hey team, revisiting this one. Any other helpful techniques?
