### ISSUE TITLE
carbonfields.net Docs link broken

### ISSUE THREAD

**Issue by nickdavis** [htmlburger/carbon-fields#706]
On the official Carbon Fields website the Docs menu link points to https://docs.carbonfields.net but I think it should point to (or redirect to) https://carbonfields.net/docs

**Comment by emohamed** [comment]
Hey @nickdavis, thanks for bringing that up - I can certainly see why this is confusing.

We used to host the documentation at https://carbonfields.net/docs, but with the latest major release(3.0), we migrated to different system(docsify), and had to move the docs to a separate subdomain. 

We left the old docs in place(because there are quite a few people using the 2.X branch, or even 1.6).

You can use the version switcher on both places to access the docs for particular version.

**Comment by nickdavis** [comment]
@emohamed thanks, I don't think I explained well though: https://docs.carbonfields.net is 404ing

**Comment by emohamed** [comment]
That's weird ... what browser are you using? 

Is it possible that you have disabled javascript for that domain?

**Comment by nickdavis** [comment]
Apologies, looks like it was a VPN issue!
