### ISSUE TITLE
Shared field

### ISSUE THREAD

**Issue by zippoxer** [htmlburger/carbon-fields#707]
## Version

  - Carbon Fields: 3.1
  - WordPress: 5.0
  - PHP: 7.3

Is it safe to re-use a field instance or an array of fields in several containers?

For example:
```php
$title = Field::make('text', 'title');

Container::make('theme_options')->add_fields([$title]);
Container::make('post_meta')->add_fields([$title]);
```

If not, then what's the recommended way to avoid defining the same field twice and still using it in a few different containers?

**Comment by emohamed** [comment]
Hey @zippoxer 

It might be fine if you keep the containers on separate pages.

However, a better approach would be to create the field in a function, and use the result in order to get a fresh instance every time:

```
<?php
function crb_create_title_field() {
    return Field::make('text', 'title');
}

Container::make('theme_options')->add_fields([crb_create_title_field()]);
Container::make('post_meta')->add_fields([crb_create_title_field()]);
```

or even something like this if you'd like to keep things easier to read:

```
class Fields {
    static function title() {
        return Field::make('text', 'title');
    }
}
Container::make('theme_options')->add_fields([Fields::title()]);
Container::make('post_meta')->add_fields([Fields::title()]);


```

The suggested approaches also have the benefit of allowing you to pass in arguments if needed down the road. 

Hope that this helps!
