### ISSUE TITLE
Button is empty or has no value text, A link contains no text

### ISSUE THREAD

**Issue by connerbw** [htmlburger/carbon-fields#717]
## Version

  - Carbon Fields:  3.1.1
  - WordPress: 5.2
  - PHP: 7.2

## Expected Behavior
❌ ➕ ✏️ buttons (and similar) with no text have an aria-label

## Actual Behavior
❌ ➕ ✏️ buttons (and similar) with no text do not have an aria-label

## Container definition
```php
// ... 
Field::make( 'color', 'crb_box_background', __( 'Background Color' ) ),
Field::make( 'association', 'crb_association', __( 'Association' ) )
	->set_types( array(
		array(
			'type'      => 'post',
			'post_type' => 'post',
		)
	) ),
```

## Steps to Reproduce the Problem

  1. Run https://wave.webaim.org/ on a page with multiselect or association
  1. Or, Inspect (Ctrl+Shift+I)

## Comments

When navigating to a button, descriptive text must be presented to screen reader users to indicate the function of the button.

If a link contains no text, the function or purpose of the link will not be presented for keyboard and screen reader users.

We recently went through a [VPAT](https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/overview-understanding-the-nature-of-what-is-required-to-design-accessibly/voluntary-product-accessibility-template-vpat/) audit and this was one of the issues brought to our attention.

**Comment by jorostoyanov** [comment]
This is now fixed in `development` and will soon make its way to a release.

Here is the commit - https://github.com/htmlburger/carbon-fields/commit/bb662f09ea416429ffc1ce3538626871854b8958

Regarding the multiselect -- we are using the `https://react-select.com/` library. I can see that there is an opened issue discussing a11y -- https://github.com/JedWatson/react-select/issues/2456

Thanks, @connerbw
