### ISSUE TITLE
Why carbon-fields delete field db records on save?

### ISSUE THREAD

**Issue by vvv3** [htmlburger/carbon-fields#789]
## Version
  - Carbon Fields: 3.1.7
  - WordPress: 5.3
  - PHP: 7.2

## Expected Behavior
Theme options and meta fields should be updated on each save action

## Actual Behavior
Theme options and meta fields deleting and inserting new ones on each save action

## Comments
I'm interested in what is the reason for this kind of behavior. This is very strange, because if I have a site with a lot of custom posts with many meta fields and they are updated frequently (for example,  real estate, etc.), then auto-increment in DB may end like that :)

I found a hook that should change this behavior - carbon_fields_should_delete_field_value_on_save, but when setting it to the false some things do not work correctly (for example, I noticed this when using the media_gallery field type). So I also don’t understand why then this hook? Or how to use it correctly?

**Comment by lstoyanoff** [comment]
Hi, I assume that the deleting is necessary due to the nature of the Carbon Fields Data Storage patterns especially for the Complex and Association fields which are saving their values in multiple rows. As long as for the `carbon_fields_should_delete_field_value_on_save` hook you can filter by the field type and for example only prevent deleting rows for the simple fields:

```php
add_filter( 'carbon_fields_should_delete_field_value_on_save', function( $should_delete, $field ) {
	$exclude_types = [ 'association', 'complex', 'map', 'media_gallery', 'multiselect', 'set' ];

	return in_array( $field->get_type(), $exclude_types );
}, 10, 2 );
```
