### ISSUE TITLE
Ability to save all Theme Options as a Array

### ISSUE THREAD

**Issue by jaredrethman** [htmlburger/carbon-fields#80]
Feature Request: Would be a cool feature to be able to save all Theme Options as an Array in the Database vs single entries. Perhaps this was done for specific reason - but performance wise (On bigger sites) it would be more beneficial retrieving 1 object vs lots of little ones.

**Comment by m1r0** [comment]
Hi @jaredrethman,

This is somewhat related to https://github.com/htmlburger/carbon-fields/issues/46. We might add an option to allow for this in a future version, but we are not planning for it right now, because it will require a major change in the core. If performance is really a problem for you, you can make a function that holds a static variable with all the needed site options and just retrieve them. Quick example:

```
function crb_get_cached_options( $option ) {
	global $wpdb;
	static $options = array();

	if ( !$options ) {
		$options = $wpdb->... // get all the needed options with one query
		// also maybe store the options in a transient?
	}

	return isset( $options[ $option ] ) $options[ $option ] : null;
}
```

**Comment by jaredrethman** [comment]
Hey @m1r0,

Thanks for your reply man. I briefly read over it. Will take a look at possibly extending the datastore (Or one of) classes to achieve this. Thanks for your snippet - have already implemented this (similar) into my setup. 

Will contribute once I get it working
