### ISSUE TITLE
Can create a new custom post type with carbon-fields but unable to see resulting posts on frontend. 404 error only.

### ISSUE THREAD

**Issue by jcklpe** [htmlburger/carbon-fields#881]
## Version

  - Carbon Fields: 1.0
  - WordPress: 5.4
  - PHP: 7.3

## Issue
I had a small request that did not sound big from a new client: take an existing custom post type (Classes), and duplicate it and make a second custom post type (Online Classes) with a few modifications. 

Their custom theme was developed using Carbon Fields. I've used ACF before but never Carbon Fields. 

I defined a container for the Remote Classes Settings for post-meta and register_post_type for the Online Classes, and the new Online Classes Post type correctly appears in the admin sidebar and I can add information to it and save it. 

But if I try to visit the page on the frontend I get a 404 erro, and I'm not sure why. 

Any clues? Is there some step here I'm missing?

**Comment by jorostoyanov** [comment]
Hi @jcklpe 

This sounds like an issue with the permalinks not being re-generated.

Every time you register a new custom post type, you have to re-save `Settings > Permalinks` so that WordPress stores the new custom post type rewrite rules.

Otherwise, you will get 404 error.

Feel free to re-open the issue if the problem persists :-)
