### ISSUE TITLE
Filter for field names

### ISSUE THREAD

**Issue by lceberg** [htmlburger/carbon-fields#9]
It would be nice to have a filter for the field names on both the `factory` methods and the `carbon_get_theme_option` / `carbon_get_*_meta` functions.

Example use case: a prefix/suffix can easily be added to the field name when setting and retrieving values on multi language sites (if, for example, the site was not initially multi-language) without rewriting all the fields.

**Comment by tyxla** [comment]
@lceberg: This sounds like a great idea at first glance. 

However it does open several potential issues if we implement such filter. Some of them are:

1. Complex fields - since prefix/suffix will be added to all fields, it will be added to the complex field subfields as well. This will be problematic to the way those fields are rendered in the plugin/theme, therefore your rendering code will require changes anyway. Main reason: the complex sub fields don't know anything about their parent, by design.
2. Some fields will probably NOT have to be translated (files, images, maps, etc.). It will be a burden to have to list all of those fields in your filter logic. 
3. There would be issues in several other situations, for example if a complex field `X` has a subfield with name `test` that needs to be translated, and the complex field `Y` has the same subfield `test`, but it does not need to be translated. As I mentioned above, the sub field does not know anything about its parent, so how would you know whether to add a prefix/suffix or not?
4. This filter would be called on every field and subfield, in every container. So this would add unnecessary overhead for all plugins/themes that don't use that filter. 
5. The prefix/suffix filter simply wont work if you want to load the same fields for multiple languages at the same time (in the same container, or in different tabs).

I'm certain that I can think of some more possible conflicts if I go in-depth with certain situations.

I believe it is a good idea to follow what WordPress does with multilingual support. They leave it to developers, declaring it as "plugin territory".

Considering that there are many ways to implement multilingual support (different container for each language, different tab for each language, language fields divided with separators, or why not side-by-side fields for each language by using `->set_width()`, not to mention many others), it is a better idea to leave that to developers. After all, we don't want to limit the developers to using a particular multilingual solution. 

So, in regards to your described use case, it would be easier and more versatile if you do the following:

1. Create a function to add a prefix/suffix to a field name. Use that function in the name parameter of your fields (only where necessary, of course).
2. Create wrapper functions for all `carbon_get_*` functions that you need. The wrapper functions would simply use the above function to generate the prefixed/suffixed name before using the `carbon_get_*` function.

Thoughts?

**Comment by lceberg** [comment]
Thanks for the response !

I was not 100% sure how this would affect all types of fields (and for multi-language we probably only need this for theme options) so I was curious about your opinion on the matter.

It might still be a good idea to have an example code for adding theme options pages for each language in the documentation for anyone who wants to use Carbon Fields on a multi-language site, but that is up to you.

I'm aware the documentation is accessible on GitHub, but an example coming from the developer will be really helpful (and accurate) as some people might find that hard to implement themselves.

**Comment by tyxla** [comment]
That is a great idea - we'll definitely consider demonstrating possible ways to implement multilingual functionality in a new documentation article or guide.
