### ISSUE TITLE
Multiple javascript issues when using Elementor

### ISSUE THREAD

**Issue by alessandrotesoro** [htmlburger/carbon-fields#909]
## Version

  - Carbon Fields: 3.1.20
  - WordPress: 5.4.2
  - PHP: Irrelevant

## Expected Behavior
No javascript issues should appear when Elementor is taking over the layout of a page.

## Actual Behavior
Uncaught ReferenceError: React is not defined
Uncaught TypeError: can't access property "combineReducers", u is undefined
Uncaught TypeError: can't access property "immer", this.cf.vendor is undefined
Uncaught ReferenceError: lodash is not defined
Uncaught TypeError: can't access property "initialize", cf.core is undefined

## Steps to Reproduce the Problem

- Create any type of CF container and add it to the page post type.
- Install & activate Elementor (any version)
- Enable the Elementor editor for the page
- Open browser's console to see the issues

## Comments
It seems the issue is caused by CF "requiring" gutenberg to be available, but of course gutenberg won't be available on pages where Elementor has taken over. I'm guessing a possible fix would be to "check" if gutenberg exists before triggering CF's scripts.

**Comment by dhalucario** [comment]
I have snooped a bit trough the CF source code. CF doesn't require Gutenberg directly but newer WP versions provide at least React which seems to be needed. I don't think CF will work without it.

**Comment by hybridvision** [comment]
I just came across this problem in Elementor's editor mode and my solution was to stop Carbon Fields from booting when on the editor page:

```php
add_action('after_setup_theme', function () {
    if (isset($_GET['action']) && $_GET['action'] !== 'elementor') {
        Carbon_Fields::boot();
    }
});
```

All I did was wrap the `if` statement around my existing call to `Carbon_Fields::boot`. The WordPress URL is something like `wp-admin/post.php?post=123&action=elementor` when in the editor mode, so that's why I check the `action` parameter.

I didn't dig any deeper into this but I haven't noticed any other issues so far with this solution. I don't think I would ever need Carbon Fields to be loaded when I'm editing with Elementor.
