### ISSUE TITLE
New Version in Release Archive?

### ISSUE THREAD

**Issue by EMembrillas** [htmlburger/carbon-fields#999]
Would it be possible to get the latest version of the plugin from the repository? :)

**Comment by emohamed** [comment]
We don't distribute carbon fields via the WordPress plugin repo because we don't want it to be updated via the WordPress admin dashboard.

The reason for that: Carbon Fields is a library that's used by developers, not a plugin to be installed by end-users(it doesn't provide anything to the end-users out-of-the-box -- a developer should write some PHP code in order to use it). Therefore, upgrading should be done by the developer, via composer or similar approach. 

If you let WordPress administrator upgrade the plugin, they might upgrade it to a new major(not backward compatible version), which conflicts with the PHP code that uses the library. This has the potential to break the whole site. 

You can still install carbon fields as a plugin(without using composer), see here: https://github.com/htmlburger/carbon-fields-plugin

You can read more about these problems here: https://carbonfields.net/2017/07/31/carbon-fields-distribution-woes/

**Comment by EMembrillas** [comment]
I was not referring to the wordpress repository. I was referring to the page https://carbonfields.net/release-archive/

**Comment by EMembrillas** [comment]
I was not referring to the wordpress repository. I was referring to the page https://carbonfields.net/release-archive/
